### ISSUE TITLE
RDF::Graph.load('uri_str') fails on a system with an http proxy

### ISSUE THREAD

**Issue by darrenleeweber** [ruby-rdf/rdf#168]
linux `env` contains a proxy config, e.g.
```
$ env
http_proxy=http://proxy.example.org:80
```

The ruby net/http library might automatically set the proxy using this env.  Maybe RDF::Graph.load does not use the proxy?

REF:  http://stackoverflow.com/questions/15792999/how-to-set-a-proxy-in-rubys-net-http

**Comment by gkellogg** [comment]
RDF::Util::File will use [RestClient](https://github.com/rest-client/rest-client) if the gem is included. According to RestClient documentation, you can do the following:

> All calls to RestClient, including Resources, will use the proxy specified by RestClient.proxy:

>      RestClient.proxy = "http://proxy.example.com/"
>      RestClient.get "http://some/resource"
>      # => response from some/resource as proxied through proxy.example.com

In the next release, I'll add options to RDF::Util::File.open_file, which is passed through from Reader.open and Graph.load, to take a `proxy` option, which will do this. But, if you use RestClient, you should be able to set it in your application and use now.

> Often the proxy URL is set in an environment variable, so you can do this to use whatever proxy the system is configured to use:

>      RestClient.proxy = ENV['http_proxy']

**Comment by darrenleeweber** [comment]
There are various issues related to proxy handling for the rest-client gem, see
https://github.com/rest-client/rest-client/issues?q=is%3Aissue+proxy

**Comment by gkellogg** [comment]
You should be able to avoid these by not including RestClient in your bundle; RDF.rb falls back to Net::HTTP. Otherwise, consider monkey-patching RDF::Util::File#open_file.

Otherwise, if you have a suggestion on how to improve native support...
