### ISSUE TITLE
Add Open Annotations vocabulary

### ISSUE THREAD

**Issue by darrenleeweber** [ruby-rdf/rdf#169]
```
vocab_sources = {
  oa:  {
    uri: 'http://www.w3.org/ns/oa#',
    source: 'http://www.openannotation.org/spec/core/20130208/oa.owl',
    strict: false
  },
}
```
Actually not sure whether it should be `strict: false` or true; have to clarify that point.  Otherwise, it works with `rake gen_vocabs`.

**Comment by gkellogg** [comment]
This might be better in the rdf-vocabulary gem. Ultimately, most gems will move over there: https://github.com/projecthydra-labs/rdf-vocab.

**Comment by darrenleeweber** [comment]
Moving this concern to rdf-vocab.
