### ISSUE TITLE
NoMethodError for `RDF::RDFS.to_graph`

### ISSUE THREAD

**Issue by darrenleeweber** [ruby-rdf/rdf#170]
```
> RDF::RDFS.to_graph
NoMethodError: undefined method `to_graph' for RDF::StrictVocabulary(http://www.w3.org/2000/01/rdf-schema#):Class
```

Documented at https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/vocab.rb#L63-L65

**Comment by darrenleeweber** [comment]
This works:  `RDF::Graph.load( RDF::RDFS ).to_ttl`

**Comment by gkellogg** [comment]
Thanks, old example. I'll get that fixed.

Graph.load is most common now.
