### ISSUE TITLE
Seeking help with a shared canvas vocabulary

### ISSUE THREAD

**Issue by darrenleeweber** [ruby-rdf/rdf#171]
Trying to create a vocabulary for http://iiif.io/model/shared-canvas/

First attempt to translate it to an RDF.rb compatible vocabulary:
https://github.com/sul-dlss/annotations2triannon/blob/master/lib/rdf/vocab/sc.rb

Probably should be generated first as an ontology.  Anyhow, seems to work, but doesn't cooperate with `RDF::Graph.load( RDF::SC ).to_ttl` for some reason.  No exceptions, just an empty string returned.

**Comment by ndushay** [comment]
the vocab loader likes things ending in .rb

**Comment by darrenleeweber** [comment]
@ndushay I figured out how to get the .ttl serialization.  The more important concern here is to have the sc.rb verified by an authority (not looking at anyone in particular @azaroth) and, preferably, generate the vocab from a public, maintained URI that hosts an ontology in .owl and/or .rdf format.

**Comment by darrenleeweber** [comment]
I'm guessing, so it would be great to get corrected, but my current understanding is that the IIIF media type profiles, for ld+json, do not amount to an ontology (vocabulary), i.e.
- http://iiif.io/api/presentation/1/context.json
- http://iiif.io/api/presentation/2/context.json

With regard to the present issue, where our concern is the shared canvas vocabulary, note that http://www.shared-canvas.org/ns/context.json redirects to http://iiif.io/api/presentation/1/context.json (i.e. they may be owl:sameAs).

**Comment by gkellogg** [comment]
I'm closing this issue without prejudice. If there are remaining vocabulary-specific issue, please raise them in the rdf-vocab repo. If there are vocabulary loader issues, please create a new issue in this repo.
