### ISSUE TITLE
Should RDF::Node#== call other#to_term ?

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#183]
Given an object that implements the `RDF::Node` interface:

```ruby
resource = Resource.new
resource.node?
# => true
resource.to_term
# => #<RDF::Node:0x3fdc3d833b38(_:g70215157365560)>
resource.to_term == resource.to_term
# => true
resource.to_term == resource
# => false
```

The culprit seems to be the hash comparison [node.rb#L151](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/model/node.rb#L151). I'm wondering whether this comparison would be better if it ran `other.to_term.hash`?

**Comment by gkellogg** [comment]
This seems like a reasonable modification.

**Comment by gkellogg** [comment]
@no-reply, can we close this issue?
