### ISSUE TITLE
RDF::Dataset as superclass of RDF::Repository

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#188]
`RDF::Dataset` should generally conform to the notion of [RDF Datasets](http://www.w3.org/TR/rdf11-concepts/#section-dataset) in RDF Concepts, using the non-mutable portions of RDF::Repository. Note that the SPARQL version of RDF Dataset differs somewhat and BNodes may not be used as graph names; this might be signaled using a `#supports?` variation.

**Comment by bendiken** [comment]
Hmm, thought we had already added `RDF::Dataset` when we discussed this last spring, but it's not on any branch I can find. To be discussed on the call tonight.

**Comment by gkellogg** [comment]
DataSet is an alias for Repository right now. I did look at separating it, as we discussed, but it seemed fairly complicated, given how much functionality is in Repository. Perhaps everything moves to Repository, but a DataSet is not mutable; still leaves the problem of loading it originally.

**Comment by gkellogg** [comment]
When creating a transaction, the repository attempts to create a snapshot which is frozen. By adding a DataSet module to it, it become a dataset and is immutable/unwritable.

**Comment by no-reply** [comment]
Closed by #267.
