### ISSUE TITLE
Deprecate `context` in favor of `graph_name`

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#189]
The `context` term is archaic, but pervasive, as a way of distinguishing the default and named graphs in a Repository or Statement. RDF Concepts uses the term [`graph name`](http://www.w3.org/TR/rdf11-concepts/#dfn-graph-name). Deprecation should be signalled in a pre-2.0 release to allow a reasonable transition time before it is removed in the 2.0 release.

**Comment by bendiken** [comment]
Note that most renamings here should probably be to `graph`, not `graph_name`--much as we don't say `subject_term` but rather just `subject`.

**Comment by gkellogg** [comment]
We need to be careful about this, since the _graph_ would seem to take an RDF::Graph, not a URI or Node. I prefer graph_name.

**Comment by gkellogg** [comment]
Updates integrated to both develop and release-2_0 branches. Use of `*_context` and `:context` as an option result in deprecation warnings on the develop branch.
