### ISSUE TITLE
Update RDF::Transaction

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#190]
* A new class `RDF::Changeset` has been added. This is meant to replace any
  previous use of `RDF::Transaction`, which in fact used to in RDF.rb 1.x
  represent more of a buffered changeset than a genuine transaction scope.

  - Instead of `RDF::Transaction.execute`, use `RDF::Changeset.apply`.
  - Instead of `RDF::Transaction#execute`, use `RDF::Changeset#apply`.

* The `RDF::Transaction` class has been substantially revamped, including
  some minor backwards-incompatible changes. These changes will mostly
  affect repository implementors, not so much general RDF.rb users.

  The changes reflect the expanded purpose of the class: instead of being a
  mere buffered changeset (for which, see `RDF::Changeset`), transactions
  are now intended to provide a proper ACID scope for repository queries and
  mutations.

  We always now also carefully distinguish between read-only and read/write
  transactions, in order to enable repository implementations to take out the
  appropriate locks for concurrency control. Note as well that transactions
  are now read-only by default; mutability must be explicitly requested on
  construction in order to obtain a read/write transaction.

  In case repository implementations should be unable to provide actual ACID
  guarantees for transactions, that must be clearly indicated in their
  documentation. Similarly, implementations should throw an exception when
  appropriate in case they don't provide write transaction support.

  - `RDF::Transaction#initialize` now takes the target repository as its
    first argument. Transactions are now always tied to a specific
    repository instance, instead of being free-floating objects as they used
    to be (for that, see `RDF::Changeset`).

  - `RDF::Transaction` now mixes in `RDF::Queryable` and `RDF::Enumerable`,
    enabling quad-pattern matches and BGP queries to execute in a proper
    transaction scope.

  - The `RDF::Transaction#context` accessor, and its aliases, have been
    removed. Transactions aren't necessarily scoped to a single graph only.

  - There is a new `RDF::Transaction#repository` accessor for retrieving the
    target repository object that the transaction operates upon.

  - There is a new `RDF::Transaction#buffered?` predicate for testing
    whether the changeset that constitutes a transaction is available for
    introspection. Particular repository implementations may support both
    options and permit the user the choice on transaction construction.

  - The `RDF::Transaction#inserts` and `#deletes` methods are deprecated.
    Instead, there is a new `RDF::Transaction#changes` accessor to retrieve
    an `RDF::Changeset` instance, which contains corresponding methods.
    For unbuffered transactions, `#changes` returns `nil`.

**Comment by gkellogg** [comment]
Also see https://github.com/ruby-rdf/rdf/blob/feature/release-2_0/CHANGES.md

**Comment by gkellogg** [comment]
@gkellogg said:
> Regarding the Transaction support for non-ACID backends; do you imagine that Changeset/Transaction can gracefully recover if such a repo raises an exception?

@bendiken replied:
Depends on whether the transaction is buffered or not (which can be a
user choice on construction); and this, of course, will also tie into
whether the backend can actually support readable intra-transaction
state or not. We'll probably need some 'flags' feature indication to
users on the capabilities provided by a particular backend. And then
have to make a choice for whether the SPARQL engine, when it would
need intra-transaction state, will explicitly bail out or instead just
silently use whatever (incorrect) state is available for reading.

**Comment by bendiken** [comment]
I have these changes in the works, will push to the 2.0 branch soon.

**Comment by no-reply** [comment]
The  relevant changes via @bendiken are: 

https://github.com/ruby-rdf/rdf/commit/9c1b86e347316762066d9e51105e3e40a6367aa4
https://github.com/ruby-rdf/rdf/blob/9c1b86e347316762066d9e51105e3e40a6367aa4/lib/rdf/transaction.rb#L21

**Comment by no-reply** [comment]
We merged initial transaction scopes & transactional repositories in #250.

Transactional reads are currently isolated as repeatable-read; we agreed to expand this to get fully (view-?)serializable transactions on the Hamster Repository.

Further, we agreed to drop `Transaction#buffered?`, replacing it with flags for isolation semantics. Perhaps something like `#isolation_level`, outputting one of `:read_uncommittted` `:read_committed`, `:repeatable_read`, `:snapshot`, or `:serializable`.

**Comment by no-reply** [comment]
We also agreed to complete the `Dataset` transition described at https://github.com/ruby-rdf/rdf/issues/188#issuecomment-175906681 as part of the transaction work.

**Comment by no-reply** [comment]
https://github.com/ruby-rdf/rdf/tree/feature/transaction-serializable & https://github.com/ruby-rdf/rdf-spec/tree/feature/serializable-transactions are the latest on this. 

Known remaining TODOs are:

  - Refactor the serializable transaction implementation to avoid `#send` calls.
  - Consider whether `#isolation_level` properly belongs to `Dataset` (should it be in `Repository`? ...elsewhere?)
  - Add documentation for isolation levels.
  - Add tests for isolation levels; most importantly: add test coverage for the specific behavior of `RDF::Repository::Implementation::SerializableTransaction`
  - Create examples for transactions.

There may be a handful of minor interface changes left to make.

**Comment by no-reply** [comment]
I went ahead and merged the above. Feedback would be useful at this point.

Particularly: Is `Dataset` scoped correctly? What should we assert about isolation levels in shared examples? Where is documentation lax?

I'm working on specs to cover gaps introduced by the addition of #267. This seems like the highest priority. At this point, we have tests to ensure that transactions are used, and that they are atomic, but the other features of the Hamster repository's transactions are untested.

**Comment by gkellogg** [comment]
Note the problem I pointed out on SPARQL::Client::Repository. Similar issues may exist for others, such as RDF::Mongo.

**Comment by no-reply** [comment]
@gkellogg do you mean the parameter changes? 

If you're referring to something else, can you link an issue?

**Comment by gkellogg** [comment]
It looks like the test is instantiating a Repository without parameters. For some repositories, such as SPARQL::Client::Repository, a `uri` parameter is necessary. In this case, to reference the URI destination (or built-in repository) for creating the connection.

There are other failures that are probably not related to this. See failures in [Travis CI](https://travis-ci.org/ruby-rdf/sparql-client/jobs/106149796). The RDF::Mongo gem has [essentially the same errors](https://travis-ci.org/ruby-rdf/rdf-mongo/jobs/106354063).

**Comment by no-reply** [comment]
The main thing I've been waiting on to close this is the isolation specs included in: https://github.com/ruby-rdf/rdf-spec/pull/56

Going to take a hack at the SPARQL/DO Repository issues now. Maybe we can get this one wrapped. :)

**Comment by no-reply** [comment]
These really look like spec issues, and not code ones. Dropping `pry` in and running the code manually works, without `except` statements.

Playing with this more, but my laptop is about to be out, and that might be all for me today.

**Comment by no-reply** [comment]
I think the merge of #279 closes this.

Note that the related #269 remains open. Graph scoped transactional read remains to be implemented.
