### ISSUE TITLE
Add Enumerable#each_node and related accessors

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#193]
Currently Enumerable has enumerators for subjects, predicates, objects, contexts and graphs, in addition to triples, quads and statements.

There are cases when it is useful to enumerate all the nodes (as in the union of subjects and objects) efficiently. Creating a node enumeration can allow an implementation to optimize this.

The default implementation may be something like the following:

    def each_node(&block)
      if block_given?
        values = {}
        (subjects + objects).uniq.compact.each(&block)
      end
      enum_node
    end

Note that `node` may be an overloaded term, as `RDF::Node` is a blank node, but defines things such as `#node?`, so an alternative would be `#each_resource`. We could also consider changing those RDF::Node'isms to clarify that they are _blank nodes_, and not any _graph node_.

**Comment by bendiken** [comment]
I think the term `RDF::Node` is quite unambiguous in an RDF context, and indeed in the original design was purposely chosen over more cumbersome alternatives such as `RDF::BlankNode`. It's only when you get to graph databases more specifically that "node" comes to have a broader meaning.

In an RDF context, subjects and objects are resources (modulo literals). Therefore I certainly favor the moniker `#each_resource` for this new method, assuming the intent is to omit literals. If literals are to be included, then both `#each_resource` and `#each_node` would be pretty dubious monikers and we might think about a more generic interface where one could specify with keywords what's to be included and what's to be omitted.

Also, as we scale up RDF.rb to larger backend stores, default implementations ought to avoid creating unnecessary materialization and garbage-collector churn. Therefore a more optimal default implementation here would be to enumerate through subjects and objects consecutively while maintaining a hash dictionary for deduplication. It's not a one-liner, but will scale better.

**Comment by gkellogg** [comment]
Yes, restating the default implementation:

```ruby
def each_resource(&block)
  if block_given?
    values = {}
    (subjects + objects).uniq.compact.select(&:resource?).each(&block)
  end
  enum_node
end
```

I think RDF::Dataset's default implementation probably uses a more optimized implementation, as would any more performant implementation of RDF::Repository. We may choose to optimize the RDF::Enuerable implementation as well, but this shows appropriate behavior. I think it is (or should be) implicit that these enumerations are unique, and don't introduce duplicates, although, currently `Emumerable#subjects` makes this optional; we may want to deprecate this behavior, or discuss anyway.

**Comment by bendiken** [comment]
While `#subjects` has optional deduplication, `#each_subject` (etc) is defined to always return distinct terms. Thus `#each_resource` should follow that pattern, and is properly a chaining of `#each_subject` and `#each_object` combined with a deduplicating filter (easiest implemented with a hash table).

**Comment by gkellogg** [comment]
@bendiken I ended up implementing `#each_term` across subjects, predicate, objects and graph_names. Another possibility would add options to limit what fields are used, and if the term is a `resource?`, `node?`, `literal?`, or `uri?`. WDYT?

**Comment by bendiken** [comment]
The `#each_term` looks fine.

As for the other question: generally, store implementations can't constrain/optimize the retrieval by resource type, meaning that any `#resource?`, `#node?`, `#literal?`, or `#uri?` filters will need to get evaluated on each resource dynamically. Given that, it doesn't make too much sense to add options for such constraints, as the more idiomatic Ruby paradigm is in any case that of in the user code applying a `#find_all` (or, conversely, `#reject`) block to the returned enumerator, and that has equivalent time complexity in this case.
