### ISSUE TITLE
Simplify constraining a repository enumeration for a single graph

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#194]
`RDF::Graph` uses `RDF::Repository` for it's data model, and does not support the notion of a `context` separate from that within the repository it comes from. In some cases, it's useful to create a context for a repository restricted to just a single graph. Right now, this might be done using the following:

```
repo.enum_graph.detect {|g| g.context == graph_name}
```

Operations such as `Enumerable#graph(graph_name)` and `Enumerable#with(graph_name, &block)` can simplify working with a single graph.

**Comment by bendiken** [comment]
The idea being that the block takes an object that's also an `RDF::Enumerable` (or superset thereof), but restricts all quad operations performed on it to be scoped to the given graph only?

**Comment by gkellogg** [comment]
Effectively. I think `RDF::Enumerable#with(graph_name)` yields those constrained quads if given a block, and returns an `#enum_for` otherwise, which then is pretty much the same as an `RDF::Graph`.

**Comment by gkellogg** [comment]
I added this with basic support in Enumerable, and simply creating the appropriate Graph in Repository and Graph.

@no-reply @bendiken This needs to be merged soon, as the rdf-spec 3.0 branch has the tests in already, but I wanted to leave it briefly from a review. If I don't hear anything from you tomorrow, I'll go ahead and merge in.

**Comment by no-reply** [comment]
This seems good. Presumably we'll want to implement repositories to optimize the `with` request. I suspect this will make things nicer for RDF::LDP...

Not sure about the clarity of `#with` as a method name, but I don't see that as a blocker, unless we have a better idea immediately.

**Comment by gkellogg** [comment]
I'm open to alternates; constrain? project? extract? graph?

**Comment by gkellogg** [comment]
Renamed to `#project_graph` in a69cb02c3357f220886f94ee244e26ed3d3bad3d.

**Comment by gkellogg** [comment]
that's not necessarily a requirement for 2.0
[2:35pm] tjohnson: * tjohnson: how does this interact with changesets?
[2:37pm] tjohnson: * bendiken: we should merge in the latest upgrades to transaction and tjohnson can look at how things look

**Comment by gkellogg** [comment]
@no-reply to verify with Blazegraph.

**Comment by no-reply** [comment]
This looks good with existing work on transactions. :+1:
