### ISSUE TITLE
RDF::WriterError writing n-triples with an empty subject URI

### ISSUE THREAD

**Issue by adolski** [ruby-rdf/rdf#197]
Apologies in advance as I am probably doing something wrong, but when I run the following script:

    #!/usr/bin/env ruby
    require 'rubygems'
    gem 'rdf', '= 1.1.13'
    require 'rdf'

    graph = RDF::Graph.new << [RDF::URI(), RDF::DC.title, "Hello, world!"]
    puts graph.to_ntriples

I get an `RDF::WriterError`:

    .../.rvm/gems/ruby-2.1.1/gems/rdf-1.1.13/lib/rdf/writer.rb:387:in `write_statement': Statement #<RDF::Statement:0x808fcf5c(<> <http://purl.org/dc/terms/title> "Hello, world!" .)> is invalid (RDF::WriterError)

However, `graph.to_ttl` and `graph.to_rdfxml` (with the necessary modules included) do work as I would expect; for example, `to_ttl` produces:

    @prefix dc: <http://purl.org/dc/terms/> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

    <> dc:title "Hello, world!" .

**Comment by no-reply** [comment]
Hi @adolski.

I believe this behavior is correct, since ntriples doesn't support the empty `<>` construction. 

http://www.w3.org/TR/n-triples/#n-triples-grammar

**Comment by adolski** [comment]
Thank you @no-reply !
