### ISSUE TITLE
Models should not be writable if frozen.

### ISSUE THREAD

**Issue by terrellt** [ruby-rdf/rdf#200]
I propose we change https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/mixin/writable.rb#L16-L18 to be
```ruby
def writable?
  !frozen?
end
```

So that if you freeze a graph or other RDF model it can no longer be modified.

**Comment by gkellogg** [comment]
I think this makes sense; right now it just returns `true`. @bendiken @no-reply, opinions?

**Comment by no-reply** [comment]
This came up because ActiveTriples previously (naively) implemented `writable?` this way. Now it uses `RDF::Writable` directly which raised this question.

On the one hand, there's `#frozen?` to tell if a thing is frozen... so it might not be unreasonable to say that `#writable?` means "this is a writable thing" as opposed to "this thing is currently writable".  I'm uncertain whether any existing code assumes that.

On the other hand, I think it's neat and usable to assume that `#writable? #=> true` means that we can safely write to a thing right now.

**Comment by terrellt** [comment]
I was playing with building a PR for this, but I'm not sure where to implement the spec. rdf-spec's writable mixin? That seems like a hard dependency on what #writable? acts like, though.

**Comment by gkellogg** [comment]
Given that it's specifically intended for concrete classes to override this, it should go in the RDF.rb mixin_writable.rb spec (which doesn't seem to be named using the _spec.rb convention, which it should).

**Comment by bendiken** [comment]
> On the one hand, there's #frozen? to tell if a thing is frozen... so it might not be unreasonable to say that #writable? means "this is a writable thing" as opposed to "this thing is currently writable". I'm uncertain whether any existing code assumes that.

I would tend to agree with this notion. As a base language feature, `#frozen?` is orthogonal to any other state of the object. Any object can be frozen, and I don't recall other libraries checking for frozenness.

**Comment by terrellt** [comment]
#201 should close this.

**Comment by no-reply** [comment]
It's noteworthy that `Object#freeze` doesn't prevent you from writing to a `Graph`.

```ruby
g = RDF::Graph.new
g << RDF::Statement(RDF::Node.new, RDF::DC.title, 'blah')
g.freeze
g.frozen? # => true
g << RDF::Statement(RDF::Node.new, RDF::DC.title, 'blah2')
g.dump :ntriples
# => "_:g69856127101340 <http://purl.org/dc/terms/title> \"blah\" .\n_:g69856129503660 <http://purl.org/dc/terms/title> \"blah2\" .\n"
```

See: http://m.onkey.org/ruby-i-don-t-like-3-object-freeze

In light of this, I'm less inclined toward this change.  If we want a way to lock a `Writable` we need to introduce our own, I think.  The old behavior in `ActiveTriples` is simply a bug.

**Comment by terrellt** [comment]
It doesn't now, but it would with this change. I always took `#freeze` as a developer's responsibility to enforce, and it seems like we have a good entry point in `#writable?`.

**Comment by bendiken** [comment]
> It's noteworthy that Object#freeze doesn't prevent you from writing to a Graph.

This being the case because `#freeze` doesn't transitively freeze referenced objects, such as `RDF::Graph#data` which is what the statements are ultimately inserted into.

**Comment by gkellogg** [comment]
Arguably, it should freeze contained statements and terms, but if they were in a shared context, this would cause problems.  We can only really affect behavior on the Writsble instance itself.

**Comment by bendiken** [comment]
> Arguably, it should freeze contained statements and terms, but if they were in a shared context, this would cause problems. We can only really affect behavior on the Writsble instance itself.

In this regard, the Ruby core docs for [`Object#freeze`](http://ruby-doc.org/core-2.2.2/Object.html#method-i-freeze) leave something to be specified:

_"Prevents further modifications to obj. A RuntimeError will be raised if modification is attempted. There is no way to unfreeze a frozen object."_

...which presumably is why https://github.com/dkubb/ice_nine and similar projects exist.
