### ISSUE TITLE
Redirects to relative locations cause failure.

### ISSUE THREAD

**Issue by demiankatz** [ruby-rdf/rdf#203]
It appears that the library cannot handle HTTP Location: redirects to relative paths, even though this is legal according to the HTTP 1.1 spec (see https://tools.ietf.org/html/rfc7231#section-7.1.2).

An example of this behavior can be found at dimenovels.org, where a request to http://dimenovels.org/Item/1 with appropriate accept headers will perform a 303 redirect to relative path /Item/1/RDF.

If you attempt to load the redirecting URI, you get an error:

<pre>
> require 'linkeddata'
=> true
> RDF::Graph.load("http://dimenovels.org/Item/1")
NoMethodError: undefined method `request_uri' for #&lt;URI::Generic /Item/1/RDF>
from rdf-1.1.14/lib/rdf/util/file.rb:143:in `block in open_url'
</pre>

If I attempt `RDF::Graph.load("http://dimenvoels.org/Item/1/RDF")` directly, it works correctly. If I change the server-side behavior to include absolute URIs instead of relative ones, that also solves the problem. However, it seems preferable to make the client library more flexible than to change server-side behavior when the server-side behavior appears to be legal (and is accepted by other clients).

Please let me know if more information is needed or if I can be of assistance in any other way. Thanks!

**Comment by gkellogg** [comment]
Thanks for the report, odd that it's taken this long to notice. I added a spec so that it's caught in all adaptors, and fixed it for Net::HTTP and RestClient.

**Comment by demiankatz** [comment]
Thanks for the quick fix!
