### ISSUE TITLE
Solutions formatting

### ISSUE THREAD

**Issue by Manicsoul** [ruby-rdf/rdf#208]
Hi Guys,

I'm trying to format the output of a query in a particular way, but am struggling. This is the output that I want to achieve:

<img width="445" alt="screen shot 2015-09-01 at 8 40 29 am" src="https://cloud.githubusercontent.com/assets/2201146/9592308/397f63b8-5085-11e5-854c-ff54231bbaf0.png">

When I run a query I get a set of solutions, the result of which ends up being:

<img width="788" alt="screen shot 2015-09-01 at 8 47 55 am" src="https://cloud.githubusercontent.com/assets/2201146/9592433/38f5ae9c-5086-11e5-9b58-c0eadb7d966e.png">

Is there a way for me to say for each distinct ?app_caps uri within a set of solutions, iterate through the bindings?

Also is there a better place (like a rdf.rb google user group) where questions like this should be posted?

Any help is greatly appreciated,
Trent.

**Comment by gkellogg** [comment]
General questions on using the Ruby RDF/SPARQL code should go to public-rdf-ruby@w3.org, as indicated in the README. We are also on IRC #ruby-rdf.

Query solutions can be retrieved programmatically using `#each_solution` from the result of a SPARQL SELECT. When retrieved over HTTP, this usually is going to be an HTML variation, as you see. Getting it programmatically sounds like what you want. You may also want to GROUP your results as part of the SPARQL query.

**Comment by Manicsoul** [comment]
Thank you for the quick response Gregg, I'll give it a try.

Also, sorry for posting in the issues section.

**Comment by no-reply** [comment]
Using SPARQL's `GROUP BY` is a good idea.

On the Ruby side, you have access to the Enumerable interface; see especially: [Enumerable#group_by](http://ruby-doc.org/core-2.2.3/Enumerable.html#method-i-group_by):

**Comment by Manicsoul** [comment]
Thanks Guys,

I managed to get the necessary data structure using the code below. If you can think of a better way of achieving this please let me know, i'm very much a beginner :).

Trent.

``` Ruby
 <%
@sse = SPARQL.parse("
PREFIX ea:  <http://www.owl-ontologies.com/Ontology1430306194.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT *
WHERE { ?bus_caps rdf:type ea:Business_Capability .
?bus_caps ea:business_capability_level '2' .
?bus_caps ea:name ?name .
?bus_caps ea:contained_business_capabilities ?level2 .
?level2 ea:name ?level2_name .
?bus_caps ea:stakeholders ?stakeholders .
?stakeholders ea:name ?stakeholders_name
}
")
   %>

<% results = @sse.execute(@repo) %>
<% results.group_by{|a| a[:name]}.each do |level1_results| %>

    <%= level1_results[0] %>

    <% level1_results[1].group_by{|a| a[:level2_name]}.each do |level2_results| %>

        <%= level2_results[0] %>

        <% level2_results[1].each do |level3_results |%>

            <%= level3_results.to_hash[:stakeholders_name] %>

        <% end %>

    <% end %>

<% end %>
```
