### ISSUE TITLE
RegexpError: premature end of char-class on JRuby

### ISSUE THREAD

**Issue by bendiken** [ruby-rdf/rdf#210]
RDF.rb 1.1.15's N-Triples/N-Quads serializer has trouble on JRuby (9.0.1.0, but probably earlier versions, too):

    lib/rdf/ntriples/writer.rb:58: warning: character class has ']' without escape
    RegexpError: premature end of char-class: /\A[ -!#-[]-~]*\z/m
                             =~ at org/jruby/RubyRegexp.java:1050
                             =~ at org/jruby/RubyString.java:1537
                         escape at lib/rdf/ntriples/writer.rb:58
                        escaped at lib/rdf/ntriples/writer.rb:281
                 format_literal at lib/rdf/ntriples/writer.rb:269
                    format_term at lib/rdf/writer.rb:424
           block in format_quad at lib/rdf/nquads.rb:141
                            map at org/jruby/RubyArray.java:2300
                    format_quad at lib/rdf/nquads.rb:141
                     write_quad at lib/rdf/nquads.rb:117
                write_statement at lib/rdf/nquads.rb:104
      block in insert_statement at lib/rdf/util/aliasing.rb:46
                             << at lib/rdf/mixin/writable.rb:34

This is due to the `RDF::Writer::ESCAPE_PLAIN ` regexp on line 44:

https://github.com/ruby-rdf/rdf/blob/1d65a2ff844ab4b004b393478b1506c8dd2a3d0a/lib/rdf/ntriples/writer.rb#L44

    ESCAPE_PLAIN = /\A[\x20-\x21\x23-\x5B\x5D-\x7E]*\z/m.freeze

In ASCII and UTF-8, `\x5B` is "[" and `\x5D` is "]". That probably has something to do with the issue, possibly indicating a JRuby bug.

Googling the issue produced only these failing specs that did record the problem some months ago:

* https://travis-ci.org/ruby-rdf/sparql/jobs/65621011
* https://travis-ci.org/ruby-rdf/rdf-rdfa/jobs/72169149

Does anyone have more information on the issue?

**Comment by bendiken** [comment]
In ASCII and UTF-8, `\x5B` is "[" and `\x5D` is "]". That probably has something to do with the issue, possibly indicating a JRuby bug.

**Comment by gkellogg** [comment]
I reported a bug in MRI 2.2.0, which was fixed for 2.2.1. I wonder if JRuby replicated the same error. RVM on Travis has been stuck at 2.2.0 as a default for mri2.0 for some time.

**Comment by bendiken** [comment]
@gkellogg, thanks. I am being led to suspect a JRuby bug, as well. Problem is, I can't reproduce this readily in a minimal script file run directly with JRuby; still working on that.

**Comment by bendiken** [comment]
This would seem to work around the problem in JRuby:

    ESCAPE_PLAIN = /\A[\x20-\x21\x23-#{Regexp.escape '['}#{Regexp.escape ']'}-\x7E]*\z/m.freeze

**Comment by gkellogg** [comment]
If it works, then fine. How does if work on MRI 2.2.0?

**Comment by bendiken** [comment]
Made the change in 6b4f301 to see how specs run on all platforms.

**Comment by bendiken** [comment]
Build [#514](https://travis-ci.org/ruby-rdf/rdf/builds/80942895) shows all green, so will release a patch release.

**Comment by bendiken** [comment]
Fixed in [1.1.16](https://rubygems.org/gems/rdf/versions/1.1.16).
