### ISSUE TITLE
RDF::Graph should use Repository#insert_statements

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#220]
`RDF::Graph` relies on [`Writable#insert_statements`](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/mixin/writable.rb#L127-L132), which always inserts statements individually. 

Some (hopefully all) `Repository` implementations that interact with upstream data implement `#insert_statements` as a single request. Using `Graph` to interact with a repository results in sending individual requests, regardless of the `Repository` implementation.

e.g., the following results in `some_statements.count` individual requests to `some_repository`:

```ruby
my_graph = RDF::Graph.new(RDF::URI('http://ex.org/my_graph'), data: some_repository)
my_graph << some_statements
```

I'm working on a fix for this.

**Comment by gkellogg** [comment]
I think the way to do this may be to redirect to Repository#insert_statements and update each statement's graph_name using map or in an enumerator, depending on the form of statements. Note that insert_statements has a special case if the first element is an Enumerable.

**Comment by no-reply** [comment]
I came up with:

```ruby
    def insert_statements(statements)
      enum = statements.respond_to?(:each_statement) ? statements.each_statement : statements
      @data.insert(*enum.map { |st| statement = st.dup; statement.graph_name = graph_name; statement })
    end
```

But planning to dig around a little more to make sure that's the best plan.

**Comment by gkellogg** [comment]
There was a recent change to make sure that it could take an enumerator, as the `*enum.map...` can create too many arguments; see https://github.com/ruby-rdf/rdf/pull/214#issuecomment-146389454.

I was thinking of something like the following:

```ruby
def insert_statements(statements)
  enum = Enumerable::Enumerator.new do |yielder|
    this.send(statements.respond_to?(:each_statement) ? :each_statement : :each) do |st|
      st = st.dup
      st.graph_name = graph_name;
      yielder << st
    end
  end
  @data.insert_statements(enum)
end
```

This allows `@data.insert_statements` to take chunks of statements to insert without evaluating everything at once.
