### ISSUE TITLE
Reinstate `text/plain` and `text/x-nquads`.

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#221]
Anything running OpenRDF/Sesame < 2.8.0 uses the old content types. Unless there's some cost to continuing to support them, my feeling is we should leave them in.

See: https://github.com/ruby-rdf/rdf/commit/ada4b791aaa681e4af6adc2b270951eafa9801f8#commitcomment-13940560 and https://jira.blazegraph.com/browse/BLZG-1096

**Comment by gkellogg** [comment]
That's unfortunate, you'd think by now things would have been more generally update. Text/plain causes the most head-ache, but we've lived with it thus far.

I'll do the revert.

**Comment by gkellogg** [comment]
Done.
