### ISSUE TITLE
Inserting statements with nil components

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#226]
As described in https://github.com/ruby-rdf/rdf-turtle/issues/11, it is possible to add invalid statements to Writable/Mutable. For example, the following test should be okay:

```ruby
it "inserts an invalid statement" do
  skip("writability") unless subject.writable?
  s = statement.clone
  s.object = RDF::Literal("non-bool", datatype: RDF::XSD.boolean)
  expect(s).not_to  be_valid
  subject << s
  expect(subject.count).to eq 1
end
```

However, adding a statement containing a nil subject, predicate, or object often creates problems, e.g.:

```ruby
g = RDF::Graph.new
g.insert([RDF::URI.new('http://example.com/x'), RDF::DC.title, nil])
g.dump(:ntriples, validate: false) #=> => "   .\n" 
```

It's worse in other serializations:

```ruby
g.dump(:ttl) #=> NoMethodError: undefined method `literal?' for nil:NilClass
```

We may want to add some notion of `incomplete?` to `RDF::Statement`, and disallow inserts of incomplete statements.

**Comment by gkellogg** [comment]
Alternatively, it may be something that just checks that each component is a term. Note that `graph_name` is not considered as part of this, but it should either be `nil` or a `resource?`.

**Comment by gkellogg** [comment]
cc/ @jcoyne

**Comment by bendiken** [comment]
@gkellogg It sounds as though you are defining the statement being incomplete as a separate condition category from it being invalid? Previously, the latter subsumed the former. Is there truly a need to be able to distinguish incompleteness from invalidity? The new extra check in `RDF::Writer#write_statement`, is somewhat superfluous, as the next line would/should have raised an error about the incomplete statement.

**Comment by gkellogg** [comment]
It's reasonable to have a Graph with invalid triples, for example, an invalid Literal (RDF::Boolean::Literal.new("foo")), but incomplete statements are somewhat different; there's really no case where adding a statement with a nil subject, predicate, or object is reasonable, whether or not validating. We can discuss further on the call.
