### ISSUE TITLE
open_file on a local file with fragment or query fails

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#235]
When opening a file such as `file://Users/foo/example.html#fragment` or `file://Users/foo/example.html?query` a ENOENT is raised, even if the base file exists. For HTTP this is handled, but not for the local file case.

**Comment by bendiken** [comment]
Curious that nobody ever reported this previously...

**Comment by gkellogg** [comment]
Indeed. I'm trying to test using tabular data from HTML tables, so the tables must be identified using fragment identifiers and are opened as such.
