### ISSUE TITLE
Repository#supports? for :literal_equality

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#242]
`:literal_equality` might be the wrong term.

Most triplestores inline literals by their value, rather than storing a value + a string expression, and fail some literal equality specs as a result.  We should make conformance for those specs optional for `RDF::Repository` impls, and add a `#supports?` flag for it.  We could then use that flag to turn off the handful of literal equality specs that test, e.g. `'01' != '1'` for repositories that don't want or need support for that "feature".

**Comment by no-reply** [comment]
@bendiken: @gkellogg and I discussed this via skype today. Your feedback is welcome. I'll probably get to this soon, since it's relevant for my Blazegraph work.

**Comment by no-reply** [comment]
Some baseline tests for literal equality support are in a branch at https://github.com/ruby-rdf/rdf-spec/compare/feature/equality.

Interestingly, `RDF::Repository::Implementation` fails several of them, due to reliance on `Array#include?`.  We should have some discussion on the level of support expected here; I'll wait on some resolution there before making the existing `01 != 1` tests conditional on `:supports?(:literal_equality)`.

Also related is the ongoing equality work connected to https://github.com/ruby-rdf/rdf/pull/260.

**Comment by gkellogg** [comment]
I think we need to allow both interpretations, and have implementations that go both ways, with tests conditional on `supports? :literal_equality`.

Perhaps a repository that does not support literal_equality always canonicalizes literals on insert, which is basically what this is saying.

**Comment by no-reply** [comment]
Closed via: #281.
