### ISSUE TITLE
Stackoverflow error with mixed case vocab constants

### ISSUE THREAD

**Issue by abargnesi** [ruby-rdf/rdf#246]
Using version `1.99.0`, the vocabulary deprecation check can yield a StackOverflowError if looking up a constant using incorrect case.

For example, `RDF::VoID` will yield a StackOverflowError. The correct casing for the constance is `RDF::VOID` so if you use that it works.

Minor point but I thought I would mention it.

**Comment by gkellogg** [comment]
Thanks, missing part of the recipe described in http://apidock.com/ruby/Module/const_missing.

**Comment by gkellogg** [comment]
Released in 1.99.0.1.
