### ISSUE TITLE
SHACL Implementation

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#268]
I've been speaking to the RDF Shapes WG & DCMI off and on about the possibility of an implementation of SHACL. 

I think that the [most recent draft](https://w3c.github.io/data-shapes/shacl/) is much closer to stability than previous releases. It might be time to start looking at serious work on this. I believe the WG needs at least one more implementation this calendar year.

Obviously, this would be an external gem, outside the core; but I wanted to raise it here since there's no space for it yet. Depending on my bandwidth in the summer and fall, I might pick this up toward mid-year. If someone else is motivated to tackle it before then, that would be very welcome.

**Comment by gkellogg** [comment]
I've been thinking about this too; it would be useful. I may have time earlier than this summer to get started.

**Comment by abrisse** [comment]
Hey @gkellogg! Any news on that implementation?

**Comment by abrisse** [comment]
Shape Expression (ShEx) seems very powerful too: https://shexspec.github.io/spec/

**Comment by gkellogg** [comment]
They're both interesting, but my time's limited right now.  It likely to do something in time for CR.

**Comment by gkellogg** [comment]
Okay, so FYI: https://github.com/ruby-rdf/shex. It's a start.
