### ISSUE TITLE
Allow RDF::Util::File::HttpAdapter.default_accept_header to be customized

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf#274]
I'm attempting to get Rails to serve linked data.  Unfortunately a `*/*` in the `Accept` header causes Rails 4.2 to just abandon content negotiation and serves up the first content type block in `respond_to`. See https://github.com/rails/rails/issues/9940

There's a PR to fix this, but it's gone stale after the contributor and a rails committer got into a disagreement about the particularities of the spec:

https://github.com/rails/rails/pull/14540

Until that is resolved, it would be great if I could configure RDF not to send `*/*` as part of the Accept header when I call RDF::Resource#fetch

**Comment by no-reply** [comment]
@jcoyne's `#fetch` is at: https://github.com/ActiveTriples/ActiveTriples/blob/develop/lib/active_triples/rdf_source.rb#L355-L368 and calls `RDF::Mutable#load`.

It looks like `#load` will faithfully pass through headers specified in the options hash. Seems like that's your best option @jcoyne. I would accept a PR to ActiveTriples that passes options from fetch to load.

**Comment by no-reply** [comment]
Closing this as an external issue (and besides, fixed by https://github.com/ActiveTriples/ActiveTriples/pull/192)
