### ISSUE TITLE
Should `RDF::Dataset` remain an abstract class?

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#284]
Currently:

``` ruby
> RDF::Dataset.new.count
NoMethodError: undefined method `each' for #<RDF::Dataset:0x00557775027bb8>
```

It seems right for `RDF::Dataset` to be a class which `RDF::Repository` directly inherits, but unfortunate to have an abstract class that can have direct instances.

My proposal would be to have `RDF::Dataset` initialize as an empty `Dataset`. I think this could be implemented as easily as `def each; Enumerator.new {}; end`.

**Comment by gkellogg** [comment]
I fine with making it a class. Note that we may want to make #supports? Cascade, as it currently doesn't use any inheritance. This could come into play if Dataset is a class that Repository inherits.

**Comment by no-reply** [comment]
> Note that we may want to make #supports? Cascade, as it currently doesn't use any inheritance.

:+1: `else super` here, and elsewhere, ought to do the trick.
https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/repository.rb#L178-L186

I'll make and test both changes.

**Comment by no-reply** [comment]
I think this was closed a long time ago by https://github.com/ruby-rdf/rdf/commit/f791472d31c0623aceeb16b318300e412dac4e71
