### ISSUE TITLE
Deprecation message re: RDF.rb 2.0 vocabulary constants

### ISSUE THREAD

**Issue by tombaker** [ruby-rdf/rdf#293]
When run, Gregg's [October 2015 `hello2.rb` example](https://ruby-rdf.github.io/presentations/HydraConnect2015/assets/player/KeynoteDHTMLPlayer.html#44)

```
require 'rdf'
require 'rdf/ntriples'
include RDF
graph = Graph.new
graph << [:hello, DC.title, "Hello, world!"]
puts graph.dump(:ntriples)
```

gets the error
```
hello2.rb:5:in `<main>': uninitialized constant DC (NameError)
```

Fixing `DC.title` to read `RDF::DC.title` gets the warning
```
[DEPRECATION] the DC vocabulary will be moved to the rdf-vocab gem
for the RDF.rb 2.0 release. Use as RDF::Vocab::DC, or include RDF::Vocab in the RDF module.
```

But fixing it to read `RDF::Vocab::DC.title` gets the error
```
in `const_missing': uninitialized constant RDF::Vocab (NameError)
```

Maybe the warning could be tweaked to make the situation clearer. Should `RDF::Vocab::DC` be used now, or only after the RDF.rb 2.0 release?

**Comment by gkellogg** [comment]
This is sort of re-writing history, as the examples were correct at the time they were given, but I've updated them to be consistent with 2.0 usage.
