### ISSUE TITLE
RDF::List#== raises NoMethodError in Ruby 2.3.x

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#304]
Ruby 2.3.0 removed an [error hiding feature in `Comparable#==`](https://bugs.ruby-lang.org/issues/7688). It turns out `RDF::List#==` was depending on this feature to return `false` for comparisons to non Array-like objects.

So in Ruby 2.3.0, we have:

```ruby
RDF::List[1,2,3] == [1,2,3] # => true
RDF::List[1,2,3] == [1,2]    # => false

RDF::List.new == RDF::URI('http://example.com/moomin') 
# NoMethodError: undefined method `to_a' for #<RDF::URI:0x2b18580e4b10 URI:http://example.com/moomin>

RDF::List.new == RDF::Node.new
#NoMethodError: undefined method `to_a' for #<RDF::Node:0x2b18593970dc(_:g47383576146140)>
```

I'm working up tests and a patch for this. I think we're just going to need a local implementation `RDF::List#==` that handles comparisons to other `RDF::Values`.

We should probably make a policy decision about whether to backport to 1.99.x. The 1.x branch never supported Ruby 2.3 officially, so I'm inclined to simply let it be unless someone wants to submit a PR.

**Comment by gkellogg** [comment]
:+1: I wouldn't bother with back-ports at this popping, unless we get a specific request to do so.

**Comment by no-reply** [comment]
Running into a related issue where:

```ruby
stmt = RDF::Statement(:s, :p, :o)

RDF::List[*stmt] == stmt  # => true; and...
stmt == RDF::List[*stmt]  # => true
```

The former is fixed in by a straight-forward patch to the main issue above, but the latter requires an additional type check in `Statement#==`, which would be executed for any otherwise true result.

The patch is incoming, but comments are welcome, especially on this second issue.
