### ISSUE TITLE
Rack 2.0.2 Doesn't support Ruby < 2.2.

### ISSUE THREAD

**Issue by gkellogg** [ruby-rdf/rdf#307]
See https://github.com/phusion/passenger/issues/1710. We should either up the required Ruby version (does anyone really need < 2.2?), or lock the version either in the gemspec, or in the Gemfile (which could distinguish on Ruby version). Thoughts?

**Comment by bendiken** [comment]
Prefer dropping support for older Rubies in case nobody needs them. These days it's pretty easy to install newer packages, even on older distros.

**Comment by no-reply** [comment]
Ruby 2.1 has been in it's security maintenance phase since March. It's probably okay to cut support from future releases.

Do we have other Rack 2.0 compatibility work to do on various gems? I haven't been able to find release notes or any kind of change summary for this update.

**Comment by no-reply** [comment]
On a related note, if we cut support for Ruby 2.1, a strict reading of SemVer requires RDF.rb 3.0.0 (see, e.g. discussion from here https://github.com/mojombo/semver/issues/148#issuecomment-25488300).

I'm inclined to disregard and make it RDF.rb 2.1.0, but we should clarify our procedure either way.

**Comment by gkellogg** [comment]
Its a minor Ruby change, so I could see 2.1.0, but the dependency is not for core functionality, so I'd say we just lock rack to 1.* for now. For RDF.rb, it's a dev dependency, but for SPARQL, and a couple of others its runtime. 

If we change the min ruby version, we'll need to change it for all dependent projects, which would be a lot of pain for little gain.
