### ISSUE TITLE
Add `Transaction#mutated?`

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#308]
This would check whether the `Transaction` has any changes from the target `Repository`. 

For the implementations we have now, the check would be easy to implement and cheap:

  - For the base class, it's `changes.inserts.empty? && changes.deletes.empty?`;
  - For the `SerializableTransaction` it's a simple object equality check on two `Hamster::Hash` instances.

For other transactions, things might not be so easy. We could recommend `NotImplementedError` in that case, or provide an API like `#<=>`'s `nil` for "not comparable".

As a motivating use case, see: https://github.com/projecthydra/ldp/issues/28#issuecomment-239031512

**Comment by bendiken** [comment]
I would generally prefer `#mutated?` over `#changed?`, as a more specific term. ("What changed? Oh, it was mutated.")
