### ISSUE TITLE
Keys for RDF::Vocabulary::Term attributes should be symbols consistently.

### ISSUE THREAD

**Issue by cdchapman** [ruby-rdf/rdf#309]
The vocabulary writer currently [only populates values with symbolic keys](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/vocab/writer.rb#L153) but the hash keys for term attributes are not all symbols, but a mix of strings and symbols. Keys that are _not_ one of the vocabulary-specific predicates (e.g. `dc:description`) are not created as symbols, but as strings, and the objects of these string-keyed predicates are consequently not being populated in generated vocabularies.

**Comment by cdchapman** [comment]
Actually I think this was already fixed in fc06d1fa6cc234845ea846f192988bc676fd9287 by @gkellogg. I thought I was running the latest code, but I am running v2.0.2. :blush:

**Comment by cdchapman** [comment]
Request for new release?

**Comment by gkellogg** [comment]
We'll get one out in the next day or so.

**Comment by no-reply** [comment]
:+1:  to a release.

I got #310 in, so we can have a real feature to ship with it. ;)

I noticed the inefficiency in #311 in the process. If we ship 2.1.0, I will probably backport this change to 2.0.x.

**Comment by cdchapman** [comment]
:+1: Thank you!
