### ISSUE TITLE
RDF::URI validation incorrectly matches RDF::Nodes

### ISSUE THREAD

**Issue by mjsuhonos** [ruby-rdf/rdf#319]
Consider e.g.
```ruby
RDF::URI.new(RDF::Node.new).valid?
=> #<MatchData "_:g70365175636340" 1:nil>
```

According to IRI validation rules the scheme part of `"_:g70365175636340"` should be invalid, i.e.
```
scheme         = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```

@no_reply has suggested the issue may be the scheme grammar regex:
```ruby
Regexp.compile("[A-za-z](?:[A-Za-z0-9+-\.])*").match '_:'
=> #<MatchData "_">
```
vs.
```ruby
Regexp.compile("[A-za-z](?:[A-Za-z0-9+-\.])+").match '_:'
=> nil
```

Is this a straightforward fix, or can someone with strong regex chops verify the implementation of the IETF syntax?

**Comment by no-reply** [comment]
I think this is fixed if we replace `[A-za-z]` with `[A-Za-z]`
