### ISSUE TITLE
Ruby 2.4 support

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#334]
There are some minor issues blocking Ruby 2.4 support:

  - `BigDecimal`s handling of invalid values (it now raises errors).
  - Possible regexp issue in `RDF::URI#canonicalize!`
  - `webmock` development dependency needs to be updated

I'm working on a patch that fixes these issues and updates the build matrix.

**Comment by gkellogg** [comment]
Working on BigDecimal and Fixnum issues.

**Comment by gkellogg** [comment]
Fixed by #335.
