### ISSUE TITLE
Regression in Reader.open in 2.2.4

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf#352]
I'm getting `no implicit conversion of nil into String` on previously working code through `RDF::Graph.load`. I'll look into this more early next week. In the meanwhile, here's the issue I'm seeing https://travis-ci.org/curationexperts/qa-ldf/jobs/211635800

```ruby
     TypeError:
       no implicit conversion of nil into String
     Shared Example Group: "an ld cache client" called from ./spec/qa/ldf/client_spec.rb:22
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/format.rb:113:in `extname'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/format.rb:113:in `for'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/reader.rb:92:in `for'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/reader.rb:184:in `open'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/mixin/mutable.rb:43:in `load'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/model/graph.rb:78:in `block in load'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/model/graph.rb:121:in `initialize'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/model/graph.rb:77:in `new'
     # ./vendor/bundle/ruby/2.3.0/gems/rdf-2.2.4/lib/rdf/model/graph.rb:77:in `load'
     # ./lib/qa/ldf/client.rb:21:in `get'
     # ./spec/support/shared_examples/ld_cache_client.rb:19:in `block (3 levels) in <top (required)>'```

**Comment by gkellogg** [comment]
Don't see what's changed here; it must be that `RDF::URI(file_name).path` is returning `nil`, which seems to happen if the URI has not path (oddly, enough). What URI are you passing?

It would seem that the right thing to do is to use `RDF::URI(file_name).path.to_s`, in any case.

**Comment by no-reply** [comment]
My uri is formatted like `http://example.com/blah/blah?subject=http://example.com/other/blah` it's possible something is going bad with escaping, or I've found an edge case that the RDF::URI regexps fail to handle.

**Comment by gkellogg** [comment]
I presume it works okay now.

```
RDF::URI('http://example.com/blah/blah?subject=http://example.com/other/blah').path
 => "/blah/blah" 
```

So, I don't see how that could have caused the problem you were seeing.
