### ISSUE TITLE
RDF::Node.uuid

### ISSUE THREAD

**Issue by jrochkind** [ruby-rdf/rdf#354]
The inline docs suggest to me that `RDF::Node.uuid` should be a thing. 

https://github.com/ruby-rdf/rdf/blob/2.2.6/lib/rdf/model/node.rb#L9

But in rdf 2.2.6, I try:

     RDF::Node.uuid

And get:

    NameError: undefined local variable or method `options' for RDF::Node:Class
	from /Users/jrochkind/.gem/ruby/2.4.0/gems/rdf-2.2.6/lib/rdf/model/node.rb:45:in `uuid'

**Comment by gkellogg** [comment]
This has been broken for a while (since 2.0). Note that you need to make sure to include either `uuid` or `uuidtools` gems, which are not in the gemspec. Please verify the behavior on the _develop_ branch, and I'll release a new version.
