### ISSUE TITLE
Accessing URIs of terms read from an RDF::Vocabulary

### ISSUE THREAD

**Issue by ijdickinson** [ruby-rdf/rdf#355]
The following code fragment is extracted from my current project. One of the things I'm doing is managing a collection of SKOS concept schemes, written in Turtle. The `RDF::Vocabulary` class has some useful methods for getting at the terms in my vocabulary, but I don't seem to be able to get the URIs of the terms cleanly. In general in RDF-Ruby, the `to_s` method on a resource returns the URI as a string, but this doesn't happen with vocabulary terms. I'm not sure if I should be using a different method to get the URI, or whether there's a bug in `to_s`.

    require 'rdf'
    require 'rdf/vocab'

    g = RDF::Graph.new << [
      RDF::Resource.new('http://data.food.gov.uk/codes/alerts/def/allergen/nuts'),
      RDF.type,
      RDF::Vocab::SKOS.Concept
    ]

    # Create an RDF vocabulary
    v = RDF::Vocabulary.from_graph(g)

    # Enumerate the concepts
    concepts = v.select { |term| term.type.include?(RDF::Vocab::SKOS.Concept) }

    puts 'Defined concept URIs:'
    concepts.each { |concept| puts concept.to_s }

## Expected

    Defined concept URIs
    http://data.food.gov.uk/codes/alerts/def/allergen/nuts

## Actual

    Defined concept URIs
    #<Class:0x00559430dffba0>http://data.food.gov.uk/codes/alerts/def/allergen/nuts

**Comment by gkellogg** [comment]
Problem seems to be that neither `class_name` nor `url` are provided when constructing the vocabulary. I think there were some reasons for not making these mandatory.

What would you like to see happen here?

**Comment by ijdickinson** [comment]
@gkellogg I totally had not noticed the `url` parameter, I think because I'm just loading the SKOS vocabulary from a local file.

Interestingly, when I set the `url` to the http URL of the actual vocabulary, the terms that I am interested in - the SKOS concepts - are not listed as `.terms()` because they are in a different namespace to the vocab file. However, I can get it all to work by:

    @vocab = RDF::Vocabulary.from_graph(@graph, url: '')

There seem to be two broad possible approaches here. One is that the use cases of `RDF::Vocabulary` broaden to encompass SKOS concept schemes and mixed namespaces. The other is that `Vocabulary` stays as it is, and some new class is added for accessing RDF codelists encoded as SKOS concept schemes. Which new class might share some code with `RDF::Vocabulary`!

I don't have a strong intuition about which is the better way to go. And unfortunately I'm drowning in deadlines at the moment, so contributing code isn't a possibility for me just now. But I'm happy to chat about possible designs though!

**Comment by no-reply** [comment]
@gkellogg: I think the behavior is as expected, except perhaps that `#to_uri` is too tolerant. Following `#to_s`, I would suggest:

```ruby
def to_uri
  RDF::URI.intern(@@uris.has_key?(self) ? to_s : nil)
end
```

Giving a null relative URI in the case that no valid URI can be built. This doesn't fix @ijdickinson's use case, but I think that he's right that it's out of scope for `Vocabulary` short of a major rewrite to allow multiple namespaces.

**Comment by gkellogg** [comment]
@no-reply, that looks good to me. Appreciate if you can handle, as I’m laid up for a while.
