### ISSUE TITLE
Strange vocabulary behaviour

### ISSUE THREAD

**Issue by ijdickinson** [ruby-rdf/rdf#357]
Hi Gregg,
I have a strange situation going on in my code, and I wonder if you can shed any light?

I have a gem that processes some input documents, and creates an RDF description of that document. As part of the processing, I load a SKOS vocabulary.  I create a constant from some terms in that vocabulary, as follows:

    PATHOGENS = AlertsVocab::Pathogen
         .new
         .terms
         .map do |t|
           t.attributes[:'http://www.w3.org/2004/02/skos/core#notation']
            .first
            .to_sym
          end
        .freeze

`AlertsVocab` is an `RDF::Vocabulary` iniitalised from a graph that loaded a Turtle file. In my unit tests for this code, the mapping works because the attributes of the terms use full URIs. All my tests pass.

However, when  Ioad the above code into my Rails app, suddenly the `attributes` of the terms are listed as qname forms:

    $ rails c
    ...
    irb(main):018:0> AlertsVocab::Pathogen.new.terms.map {|t| t.attributes}
    => [{:label=>["Campylobacter spp"], :vocab=>RDF::Vocabulary(), 
    :"skos:prefLabel"=>["Campylobacter spp"], :"skos:notation"=>["campylobacter"]

which makes the `PATHOGENS` constant computation fail.

So my question: what would make the attributes of the vocabulary appear as full URIs in one context, and qnames in another?

Appreciate any suggestions!

**Comment by no-reply** [comment]
@ijdickinson Sorry it has taken so long to respond to this. Can you provide a bit more information about your vocabulary setup? 

It's not clear to me what is going on with `AlertsVocab::Pathogen.new`, and steps to reproduce would help me figure out what's going on; even if we can't actually reproduce the unexpected state.

**Comment by gkellogg** [comment]
Sorry, I missed this too. I think I pointed you to [this bit of code](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/vocabulary.rb#L664-L725). Basically `Term` keeps the attributes using the hash in as compact a form as possible, which means using symbols or PNames for attributes. We could consider adding another method to do what you need. Short of that, you're probably going to need to use `#each_statement`, which could be wrapped in a `Queryable` to get more direct access.

**Comment by gkellogg** [comment]
@ijdickinson I wanted to see if you had some thoughts on how we can better support SKOS and the usage patterns that would be generally useful. Bearing in mind that the `Term` implementation is based on a `Hash`, how would you like to be able to iterate and use such attributes.

One thought would be to override `Term#attributes` with a `#[]` accessor, which allows for greater flexibility of lookup, allowing absolute URIs, PNames, and and vocabulary-relative terms.

Values are strings, and knowing if they are datatyped literals, or URIs is attribute-specific and/or heuristic as defined in [`Term#each_statement`](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/vocabulary.rb#L667-L719). I could imagine extracting this logic for something like an `#attributes#[]`, or more specific, accessor.

Do you have any other thoughts are use cases?

**Comment by ijdickinson** [comment]
Sorry @gkellogg and @no-reply, I've been completely buried in client work then taking some much-needed downtime. I'll see if I can dig out a repeatable test case.

In terms of use cases for SKOS vocabularies, we use SKOS primarily for two reasons:

* a controlled vocabulary where we want to have a URI for each of the terms, and a URI for the whole collection. For example, see [bathing water quality codes](http://environment.data.gov.uk/def/bathing-water-quality/compliance)

* a hierarchical structure

In the first case, we will often abbreviate the term using a slug, for example in an API call or embedded in a UI, corresponding to the `skos:notation`. So being able to conveniently derference the term from the notation would be handy.

In the second case, navigating up and down the hierarchy using `skos:narrower` and `skos:broader` relations would be really handy!

Sorry that's a bit brief, I can expand the use cases some more if that's helpful.

**Comment by gkellogg** [comment]
@ijdickinson check out the [vocab-update](https://github.com/ruby-rdf/rdf/tree/feature/vocab-update) branch. It allows terms to use many SKOS properties natively. This should allow you to, say, have a Term for http://environment.data.gov.uk/def/bathing-water-quality/compliance and follow links for things like `hasTopConcept` to get an array of Terms, which are presumably Concepts. It might look something like the following:

```ruby
concept = RDF::Vocabulary::Term.new("http://environment.data.gov.uk/def/bathing-water-quality/compliance", attributes: {
  type: "skos:ConceptScheme",
  comment: "A collection of Bathing Water Compliance Classification codes",
  hasTopicConcept: [f, c, ...],
  note: " A SKOS ConceptScheme for bathing water compliance classification codes."
})

f = RDF::Vocabulary::Term.new("http://environment.data.gov.uk/def/bathing-water-quality/f")
c = RDF::Vocabulary::Term.new("http://environment.data.gov.uk/def/bwq-cc-2012/C")

concept.hasTopicConcept #=> [f, c]
```

Also, Term attribute values can be terms with anonymous subjects (BNodes), which seems to be a common pattern, so:

```ruby
term: :af,
  type: "jur:Country",
  isDefinedBy: "http://eulersharp.sourceforge.net/2003/03swap/countries#",
  "skos:exactMatch": [
    Term.new(nil,
      type: "skos:Concept",
      inScheme: "iso3166-1-alpha-2",
      notation: "ax"),
    Term.new(nil,
      type: "skos:Concept",
      inScheme: "iso3166-1-alpha-3",
      notation: "ala")
  ],
  "foaf:name": "Aland Islands"
```

Work still needs to be done on parsing vocabularies to create the embedded terms, but it should be straight forward. It would be worth getting your feedback on if this like like it might make working with SKOS vocabularies easier.

/cc @no-reply

**Comment by gkellogg** [comment]
@ijdickinson Recent updates now have the attribute values being objects, such as terms and lists, which should allow for in-memory navigation. This was quite hampered because of the recursive nature of RDF.rb classes relying on vocabulary terms, which are also defined in terms of other RDF vocabulary classes, but that's been figured out (using some clever lazy evaluation of passed blocks).

To make this happen, we now have both embedded terms and lists supporting things like `owl:unionOf`. You should be able to serialize a SKOS graph from a vocabulary and then read it back in to navigate within that graph, and to other loaded concept graphs.

Many SKOS properties now have native expression as term attribute keys, as well.

I'm going to merge this in, but please let me know if there are improvements that can help.
