### ISSUE TITLE
Unexpected difference between Node.new and Resource.new as b-nodes

### ISSUE THREAD

**Issue by ijdickinson** [ruby-rdf/rdf#358]
I needed to create a bNode for my graph. Before properly checking the docs, I thought that `Resource.new()` would be the right way to create a bNode. It does create an anonymous node, but that node doesn't behave the way I expected in the Turtle serialisation.

## Test code: 

    require 'rdf'
    require 'rdf/turtle'

    g = RDF::Graph.new
    subj = RDF::Resource('http://foo.bar/subj')
    p = RDF::Resource('http://foo.bar/p')

    b_node_node = RDF::Node.new
    b_node_res = RDF::Resource.new

    g << RDF::Statement(subj, p, b_node_node)
    g << RDF::Statement(b_node_node, RDF::RDFS.label, 'bNode via Node.new')

    g << RDF::Statement(subj, p, b_node_res)
    g << RDF::Statement(b_node_res, RDF::RDFS.label, 'bNode via Resource')

    puts(RDF::Turtle::Writer.buffer(
      base_uri: 'http://foo.bar/',
      prefixes: {
        rdfs: RDF::RDFS.to_s
      }
    ) do |writer|
      g.each_statement do |statement|
        writer << statement
      end
    end)

## Result

    $ ruby ~/temp/ttl-bnode-test.rb 
    @base <http://foo.bar/> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

    <subj> <p> <>,  [ rdfs:label "bNode via Node.new"] .

    <> rdfs:label "bNode via Resource" .

## Expected

Naively, I would have expected both labels to be reachable from `:subj`, but they aren't. It's quite possible - or likely! - that I'm doing something wrong in creating a bNode with `Resource.new`, but perhaps there should be a warning issued?

**Comment by gkellogg** [comment]
Looking at [`Resource.new`](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/model/resource.rb#L12-L18), if given an empty or null argument, etc creates a URI, in this case a relative URI. It will create a BNode if given something like `"_:"`.
