### ISSUE TITLE
RDF::URI.new('').present? returns true

### ISSUE THREAD

**Issue by ArthurWD** [ruby-rdf/rdf#367]
Shouldn't this return false?

**Comment by gkellogg** [comment]
I find no method named `#present?` anywhere in RDF.rb. Could you be mixing it in somehow?  Try the following:

    RDF::URI.new('').method(:present?).source_location

**Comment by no-reply** [comment]
`Object#present?` is part of the Rails API. It's the inverse of `blank?`, which is true if `!object` or `#empty?` is implemented and `true`.

In this case, I think `RDF::URI('')` and `RDF::URI(nil)` are correctly `present?`. They are usable as null relative URIs.
