### ISSUE TITLE
serializers also outputting xsd:string?

### ISSUE THREAD

**Issue by bertvannuffelen** [ruby-rdf/rdf#374]
Hi, 

from the readme I get this: 

> There are substantial and somewhat incompatible changes to {RDF::Literal}. In RDF 1.1, all literals are typed, including plain literals and language tagged literals. Internally, plain literals are given the xsd:string datatype and language tagged literals are given the rdf:langString datatype. Creating a plain literal, without a datatype or language, will automatically provide the xsd:string datatype; similar for language tagged literals. Note that most serialization formats will remove this datatype. Code which depends on a literal having the xsd:string datatype being different from a plain literal (formally, without a datatype) may break. However note that the #has\_datatype? will continue to return false for plain or language-tagged literals.

My question: is it possible to change the behaviour and get the xsd:string being outputted? Eventually via an option?

**Comment by gkellogg** [comment]
This would be on a per-writer basis. The practice in RDF 1.1 is to omit the `xsd:string` datatype for literals without language or any other datatype. Is there a particular serialization where you'd like to see this option?

**Comment by bertvannuffelen** [comment]
Ok, I understand. Thanks for your time to provide me with the insights. I will have a relook at my setup and take next steps from there.
