### ISSUE TITLE
Way to match a URI pattern for http/https issues?

### ISSUE THREAD

**Issue by typhoon2099** [ruby-rdf/rdf#393]
I'm trying to parse microdata on a few pages but I have hit an issue where some schema.org references are using https and others are using http. I would like to create a query that covers both situations but I haven't found a neat solution. Can RDF::URIs be defined using a regex? Or do I need to create two queries and check both for each graph I want to parse?

**Comment by gkellogg** [comment]
That will work, or you can use `RDF::Vocab::Schema` for those that use http, and create another vocabulary for the https versions. Really, the problem is that their data is invalid.

**Comment by gkellogg** [comment]
The use of https in Microdata (ie., `https://schema.org/Thing`) is invalid, but if you want to handle it, this would be the way to go.

Might be easier to formulate your queries using SPARQL, and using the sparql gem.
