### ISSUE TITLE
ruby gems docs redirect to ruby-do

### ISSUE THREAD

**Issue by ConorSheehan1** [ruby-rdf/rdf#395]
The docs on ruby gems redirect to rdf-do.  
I can't see anything in the source code that would cause it, so it might just be a ruby gems issue.

![docs_redirect](https://user-images.githubusercontent.com/16896053/56304154-6b210d80-6135-11e9-9d21-f8cc849c3cb0.gif)

**Comment by gkellogg** [comment]
It looks like some issue with RubyGems, as we don't provide them a documentation URL. However, I can update the gem spec to do this, which should fix the issue.

**Comment by gkellogg** [comment]
Fixed via 95c82dea15a74f8912380895143604825aae4b59.
