### ISSUE TITLE
Getting child Nodes

### ISSUE THREAD

**Issue by typhoon2099** [ruby-rdf/rdf#397]
How can I read the child Nodes of a known Node? I have a complex Query for finding Product data but I'm running into issues with it now and want to strip back the Query to just find the Product node, and then traverse down to search for the properties that I need. So far I haven't been able to find any methods which do this.

**Comment by gkellogg** [comment]
By this, you mean the object IRIs of statements having a common subject, or all of the properties of those objects?

Again, probably easier to formulate in SPARQL, but it can be done using the query mechanism. You might also be interested in the [Concise Bounded Description](https://www.rubydoc.info/github/ruby-rdf/sparql/RDF/Queryable#concise_bounded_description-instance_method) method from the sparql gem, which is useful when objects are blank nodes, or there are lists involved.

In SPARQL, you could so something like the following:

```sparql
DESCRIBE ?o
WHERE {
 <known_iri> ?p ?o .
}
```

**Comment by typhoon2099** [comment]
Well I had just kind of assumed that there was some way to read all the related Nodes from a known Node without having to specify what I'm looking for. If you look at the other ticket I raised you'll see specifically what I'm trying to achieve.

**Comment by gkellogg** [comment]
You can either use the `RDF::Query.new {}` pattern, or pass in a hash to get solutions back. In a hash, symbols act as variables, so to get all the predicates/objects for subjects that are objects of some other known URI, you could do something like the following:

```ruby
dataset.query({
  RDF::URI("some_well_known_uri") => {
    p: {
      o: {
        p2: :o2
      }
    }
  }
})

query.execute(dataset)
```

You could also provide this to `RDF::Query.new` and execute the resulting query object against the dataset.

To use the `pattern` mechanism, you can link patterns together using their variables.

```ruby
query = RDF::Query.new do
  pattern [RDF::URI("some_well_known_uri"), :p, :o)]
  pattern [:o, :p2, :o2]
end
```

The interface is all about managing graphs and datasets; while there are some interfaces in `RDF::Queryable` to work directly, the paradigm is typically to query over these datasets to get what you want.

You can get statements out of a result set by iterating over the result set to construct statements from the solution bindings.

The SPARQL gem does a lot of this for you with a fairly straightforward syntax, but sometime's it's good to do things using the low-level RDF interface.
