### ISSUE TITLE
A Time should be typed as XMLSchema#dateTime

### ISSUE THREAD

**Issue by ArthurWD** [ruby-rdf/rdf#400]
Ruby does not have a class which represents a time without date. A Tod::TimeOfDay provided by the tod gem would justify XMLSchema#time, but the default Time class always includes a Date.

The mismatch between the Ruby Time and the XMLSchema#time causes information loss. For example, ActiveRecord converts a postgres datetime column to a ActiveSupport::TimeWithZone. When serializing that attribute, we lose the date part of the value.

#399 fixes this issue by using XMLSchema#dateTime. However, the current implementation is around for years, so this might break applications. 

Of course, I can hack my way into a solution by prepending the Literal#new method, but I believe this PR is a logical solution since it is just a better mapping.

We could add a configuration option, so developers may choose their own implementation.

**Comment by gkellogg** [comment]
Closed via #399.
