### ISSUE TITLE
SHACL Implementation

### ISSUE THREAD

**Issue by saumier** [ruby-rdf/rdf#407]
I am hearing more and more about [SHACL](https://www.w3.org/TR/shacl/), rather than ShEx to validate the shape of RDF graphs.  Here is one of several [comparisons](https://figshare.com/articles/ShEx_and_SHACL_compared/6449648).
I noticed that this same request/issue was raised in [issue 268](https://github.com/ruby-rdf/rdf/issues/268).  Any talks or plans for a SHACL implementation?

**Comment by gkellogg** [comment]
I haven’t even had time to keep up with ShEx. It would be great to have a SHACL implementation, but not sure when I might have the time to get to it. Contributors welcome.

**Comment by saumier** [comment]
This is still a high priority for me.  SHACL is picking up more and more.  If I can find contributors I will point them here 
;-)

**Comment by gkellogg** [comment]
Thanks, that would be great! I don’t have the bandwidth to start another big project right now.

**Comment by gkellogg** [comment]
I've begun a project template, and will likely do some more setup for the basic project infrastructure and layout design considerations to fit in with the general RDF.rb architecture.

Please move any further discussion to https://github.com/ruby-rdf/shacl/issues.
