### ISSUE TITLE
RDF::Vocabulary wasted effort on entailment

### ISSUE THREAD

**Issue by doriantaylor** [ruby-rdf/rdf#411]
Just using `rbspy` to check out what happens with `RDF::Vocabulary` when entailment is invoked. `method_missing` and `require` appear to both get hit potentially thousands of times only to turn up nothing, causing the computer to do a lot of unnecessary work.

It looks like `property?` and `class?` get run a lot during entailment, which in turn run `self.type`, which invokes `method_missing`, which calls `attribute_value`, which calls `expand_pname`, which calls `RDF::Vocabulary.each`, which calls `require` over all the contents of `RDF::VOCABS`, which, from what I can tell, even though it only runs over a known set of resources, is far from costless when run thousands of times.

I submit it makes sense to reconsider the approach here:

* The idiom `RDF::Vocabulary.each.detect` could probably stand to be a hash lookup instead of iterating over an enumerator.
* For `method_missing` maybe it would make sense to inline those methods?
* For the calls to `require`, maybe establish a cheaper bypass?

Thoughts?

**Comment by gkellogg** [comment]
The code is ripe of optimization. Care to take  it on?

**Comment by gkellogg** [comment]
One thing I think we can do is to rewrite `RDF::Vocabulary.each` to not automatically require each vocabulary, but perhaps create something alongside `@@subclasses` which maps the prefix to the vocabulary URI and defer loading the actual vocabulary until it is required by `#pname` or similar. There's certainly quite a bit of work done that shouldn't be necessary unless the vocabulary is actually used.

Entailment is a bit more tricky, though, as it needs to look at various RDFS predicates to know if there is a relationship. We can subset some by depending on `owl:includes`, which I think we do, but otherwise, it's difficult to know exactly what vocabularies to look in to find relationships.

Previously, I looked at the rdf-reasoner gem to see if there might be a way to whitelist vocabularies to reason over, but the key is probably to do something in `RDF::Vocabulary` to subset `@@subclasses`.

**Comment by doriantaylor** [comment]
I hav an engagement going for another couple months so it will be contingent on how much this particular snag enrages me between now and then. ;)

Otherwise it'll have to wait until I'm done.

**Comment by doriantaylor** [comment]
From what I can tell the operations invoked through entailment are just really expensive; it would be manageable to run them thousands of times if they were just plain cheaper to run.

**Comment by gkellogg** [comment]
I'll work on some in-progress PRs to address. You might monitor and provide suggestions along the way.

**Comment by gkellogg** [comment]
@doriantaylor do you have a particular dataset/vocabulary you ran this over? What entailments were you using?

**Comment by doriantaylor** [comment]
By the look of it it's when `RDF::Reasoner.apply(:rdfs, :owl)` is executed.

**Comment by gkellogg** [comment]
I haven't started on this quite yet, but I think, among other things, a way to restrict the vocabularies that `RDF::Vocabulary.each` iterates over will be important. Probably an operation that sets a class variable which acts in place of `@@subclasses` will help. Without this, it will look at all vocabularies to look for sub-classes/properties, which is part of what makes it so expensive. Generally, you know the set of vocabularies you're interested in.

**Comment by gkellogg** [comment]
@doriantaylor I've made a number of optimizations, and re-worked how vocabularies get loaded.

Reasoning time was previously dominated by loading vocabularies. This can be substantially reduced by using `RDF::Vocabulary.limit_vocabs` before they've been loaded. This will only return the specific vocabularies you ask for, and seems to reduce loading time quite a bit.

If you clone the rdf-reasoner gem, there is a `script/reason` script which can take --profile and --vocabs arguments to perform entailments over a given graph and give you a profile output to see where time is going.

Let me know if this works better for you can I can release gem updates.

**Comment by doriantaylor** [comment]
Cool! I'll try it soon.

**Comment by doriantaylor** [comment]
It's like night and day. How does it work?

**Comment by gkellogg** [comment]
Magic! :)

It does a lot less iterating through vocabularies, which cause them to be loaded, which is expensive.

There are probably issues with ad-hoc vocabularies and using pname, though.

**Comment by doriantaylor** [comment]
does it still load them once though?

**Comment by gkellogg** [comment]
It avoids loading the vocabularies, where it can. And, you can force it to limit with `limit_vocabs`
