### ISSUE TITLE
Is it possible to configure deterministic serialisation?

### ISSUE THREAD

**Issue by berezovskyi** [ruby-rdf/rdf#412]
I am trying to put some Turtle files under VCS and the output keeps changing a lot. I know the same problem was raised many times in the RDF community, incl. JSON-LD and there is no consensus on this at the RDF spec level yet, but I was curious if RDF.rb could offer an `RDF::Writer.dump` flag (e.g. `quasi_deterministic: true`) to make serialisation as deterministic as possible.

The most annoying problem right now is that the ordering of the objects when a repeated property is used is quite arbitrary. Example:

```
:s :p :o1, :o2, :o3 .
```

```
:s :p :o3, :o1, :o2 .
```

I was thinking if we could sort the object URIs lexicographically (and place URIs before/after bnodes), this would be a good first step?

**Comment by gkellogg** [comment]
See https://rubygems.org/gems/rdf-ordered-repo, which uses native hashes which preserve insert order. It may not be as performant, although there are probably some improvements that could be made by better leveraging transactions.
