### ISSUE TITLE
Support arbitrary vocabs + more robust `expand_pname`

### ISSUE THREAD

**Issue by doriantaylor** [ruby-rdf/rdf#413]
Moving discussion of ruby-rdf/rdf-reasoner#7 here. Thinking it might be necessary still to be able to register vocabs with `RDF::Vocabulary`. Ensuring `rdf/vocab` is loaded first is the first step, but I feel like there needs to be some way to register vocabs outside the `RDF::Vocab` tree.

To restate the problem, `RDF::Vocabulary.expand_pname` is ostensibly not capable of resolving vocabularies that are not already listed in either `RDF::VOCABS` or `RDF::Vocab::VOCABS` (via `rdf/vocab/extensions`). It seems like it makes sense to create some kind of `RDF::Vocabulary.register` class method or something to get new entries into the dictionary.

I will give it some thought…

**Comment by gkellogg** [comment]
I think your idea of an explicit register_vocab is good. That could be added to every vocabulary definition to be sure it shows up. The code in rdf-vocab is key for using vocabularies without loading them.

**Comment by doriantaylor** [comment]
I have gone and written the code but noticed a couple test failures:

1) `mixin_enumerable_spec.rb` has typos in the url schemes of the test data which I corrected,
2) `vocabulary_spec.rb` requires the patched `rdf-vocab` in order to pass.

**Comment by gkellogg** [comment]
@doriantaylor I think we can close this now.
