### ISSUE TITLE
RDF::NTriples::Reader does not `require 'strscan'`

### ISSUE THREAD

**Issue by doriantaylor** [ruby-rdf/rdf#415]
Just had a random crash with `RDF::NTriples::Reader`; it references `StringScanner` but doesn't require `strscan`. Adding `require 'strscan'` made the crash go away.

(Also not sure why this never happened before just now.)

**Comment by gkellogg** [comment]
StringScanner is used by EBNF, which is used by rdf-turtle. The rdf-turtle dependency in the Gemfile should be enough to bring this in.

However, the EBNF gem doesn't have this in its Gemfile.lock, either, because StringScanner is in the standard library, so not sure why you'd see this.

**Comment by gkellogg** [comment]
Okay, but StringScanner is used directly by the N-Triples library, and should, indeed, have it's own require of 'strscan', which may have been included due to other loaded dependencies.

**Comment by gkellogg** [comment]
Looks like this was fixed in 7449b0a60a78a8abb8dbfa7da2dd83f6e4444bb4.
