### ISSUE TITLE
Comparing two repositories

### ISSUE THREAD

**Issue by PMAxelDelsol** [ruby-rdf/rdf#427]
Currently, we can compare two RDF::Graph using the equivalente operator `==`.

Are there any reasons we can not compare 2 RDF::Repositories ?
At first, it seems we could just check the statements but there may be some hidden edge cases.

**Comment by gkellogg** [comment]
Blank nodes prevent two repositories from being directly compared. RDF defines isomorphism for graphs, and there is an rdf-isomorphic gem you can use to compare graphs or repositories. You can also use rdf-normalize to create a canonical N-Quads representation which will be the same for isomorphic graphs.

**Comment by PMAxelDelsol** [comment]
Thanks, you answered my question perfectly !
