### ISSUE TITLE
Is it possible to change the standard prefixes?

### ISSUE THREAD

**Issue by wu-lee** [ruby-rdf/rdf#431]
This is a question, essentially a request for documentation, if possible, or a feature request if not.

Is it possible to change the prefixes used for the standard vocabularies defined here, such that RDF::URI#qname uses them when shorting URIs (and #pname, RDF::Vocab.exand_pname etc.)?

Using my case as an example, I would like to use the prefix `dcterms` instead of `dc`, and `dc` instead of `dc11`. This is because I want to work with TTL files with a pre-existing choice of prefixes which differ from the ones used in RDF::Vocab. (Both read and write them.)

I have found the RDF::Vocabulary.register method, which seems to allow adding new prefixes, and RDF::Vocabulary.limit, which are candidates when combined, but I am uncertain if these are designed to do this job reliably.

**Comment by gkellogg** [comment]
@wu-lee See if that change works for you, and it will be in the next release.
