### ISSUE TITLE
change from DateTime < Literal to DateTime < Temporal breaks downstream customization

### ISSUE THREAD

**Issue by elrayle** [ruby-rdf/rdf#434]
FYI... 3.2.5 includes a breaking change

_NOTE: This is a very old monkey patch.  We are evaluating whether is still required.  I thought you would want to be aware of the impact on downstream customizations with the change of superclass._

Reference: [samvera/active_fedora/issues/497](https://github.com/samvera/active_fedora/issues/497) - original discussion where the monkey patch was recommended.

### Code at 3.2.4

We are doing the following monkey patch in a class that runs at startup.  This is the full patch that works with 3.2.4.
```
# Monkey patching RDF::Literal::DateTime to support fractional seconds.
# See https://github.com/projecthydra/active_fedora/issues/497
# Also monkey patches in a fix for timezones to be stored properly.
module RDF
  class Literal
    class DateTime < Literal
      ALTERNATIVE_FORMAT   = '%Y-%m-%dT%H:%M:%S'.freeze
      DOT                  = '.'.freeze
      EMPTY                = ''.freeze
      TIMEZONE_FORMAT      = '%:z'.freeze

      def to_s
        @string ||= begin
          # Show nanoseconds but remove trailing zeros
          nano = @object.strftime('%N').sub(/0+\Z/, EMPTY)
          nano = DOT + nano unless nano.blank?
          @object.strftime(ALTERNATIVE_FORMAT) + nano + @object.strftime(TIMEZONE_FORMAT)
        end
      end
    end
  end
end
```
[full monkey patch for 3.2.5](https://github.com/samvera/active_fedora/blob/main/lib/active_fedora.rb#L11-L37)

### Exception with 3.2.5

With the change from RDF 3.2.4 to 3.2.5, an exception is thrown...
```
`<class:Literal>': superclass mismatch for class DateTime (TypeError)
```

### Patch for 3.2.5
As mentioned at the start, this patch is very old.  We are looking at just skipping it for 3.2.5 until we have a chance to re-evaluate the patch.

To do this, we've put in place a check of the superclass and don't apply the patch unless the superclass is RDF::Literal.
```
#
# RDF 3.2.5 changes the superclass of DateTime to RDF::Temporal
# TODO: Determine if this monkey-patch is needed even with RDF pre-3.2.5 (All the tests pass without it)
if RDF::Literal::DateTime.superclass == RDF::Literal
```

**Comment by gkellogg** [comment]
Also, the `< Literal` in your code is likely unnecessary for a monkey patch, but a refinement could be something else to consider.

**Comment by gkellogg** [comment]
Another thing to consider would be adding an optional argument to `#to_s` to specify a format string to use rather than FORMAT (although, the timezone information isn't included in the FORMAT string any longer, which was never consistent, but is appended to the resulting format string).

For example:

```
def to_s(format=nil)
  if format
    @object.strftime(format).sub('.000', '') + self.tz
  else
    @string ||= (@object.strftime(self.class.const_get(:FORMAT)).sub('.000', '') + self.tz)
  end
end
```

Note that `#to_s` is now implemented in Temporal, so this works for all related classes.

**Comment by elrayle** [comment]
@gkellogg Thanks for the suggestions.  We'll look into this.

**Comment by cjcolvar** [comment]
@gkellogg Thanks for the advice!  I ended up skipping the explicit subclassing in our monkey-patch for now.  I'll see if there is anything that could be fed back upstream to avoid the monkey-patch in the future.
