### ISSUE TITLE
RDF::Vocabulary.find on RDF vocab returns RDF class

### ISSUE THREAD

**Issue by doriantaylor** [ruby-rdf/rdf#436]
Try:

```ruby
RDF::Vocabulary.find 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
# => RDF
```
Not sure how this is getting snuck in there. This is 3.2.7.

**Comment by doriantaylor** [comment]
oh, wait, [it's in there deliberately](https://github.com/ruby-rdf/rdf/blob/develop/lib/rdf/vocabulary.rb#L742). I tripped over this. Was this on purpose?

**Comment by gkellogg** [comment]
That would be due to the hack I mentioned. But, given that symbols from RDFV are imported into RDF (IIRC), is there some specific problem that results from this?
