### ISSUE TITLE
`RDF::Literal::Date` produces an invalid value when initialized with a `Time` object

### ISSUE THREAD

**Issue by Richard-Degenne** [ruby-rdf/rdf#447]
# Reproduction steps

```ruby
time = Time.parse('2024-10-07T14:25:40Z')
date = RDF::Literal::Date.new(Time.now)
puts date.value
```

## Expected result

```
"2024-10-07"
```

## Actual result

```
"2024-10-07Z"
```

# Notes

This is kinda bad because the produced value is not a valid date string according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601), as dates are not supposed to include timezone indicators.

**Comment by gkellogg** [comment]
RDF uses XSD  Datatypes, where [date](https://www.w3.org/TR/xmlschema11-2/#date) has an optional timezone.

> [18]   dateLexicalRep ::= [yearFrag](https://www.w3.org/TR/xmlschema11-2/#nt-yrFrag) '-' [monthFrag](https://www.w3.org/TR/xmlschema11-2/#nt-moFrag) '-' [dayFrag](https://www.w3.org/TR/xmlschema11-2/#nt-daFrag) [timezoneFrag](https://www.w3.org/TR/xmlschema11-2/#nt-tzFrag)?

**Comment by gkellogg** [comment]
A reasonable change would be to not emit the timezone from a native Date, DateTime, or Time representations, but preserve it if specified directly.

**Comment by Richard-Degenne** [comment]
Huh, that's interesting, thanks for finding out the original specification.

I discovered the issue when the output value caused issues with Elasticsearch, whose `date_optional_time` format specifies:

> A generic ISO datetime parser, where the date must include the year at a minimum, and the time (separated by T), is optional. Examples: `yyyy-MM-dd'T'HH:mm:ss.SSSZ` or `yyyy-MM-dd`.
>
> -- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html

Maybe I should open an issue against them. 🙃
