### ISSUE TITLE
rdf.rubyforge.org has broken links

### ISSUE THREAD

**Issue by tommorris** [ruby-rdf/rdf#93]
The tutorials section of http://rdf.rubyforge.org/ has broken links, but it works in the repo.

**Comment by gkellogg** [comment]
@bendiken can we make all of the rubyforge pages fir RDF.rb and related redirect either to their GitHub pages, the rubygems entry (which references documentation), to documentation on rubydoc.info, or determine some strategy for this in general? The permanence of out-of-date information on rubyforge continues to bite.

**Comment by bendiken** [comment]
Since rubyforge.org is defunct for some time now, I'm surprised the http://rdf.rubyforge.org/ subdomain still exists and still hosts content. I will endeavor to locate and test the previous SFTP login credentials for it, to see whether we can make any changes.

**Comment by bendiken** [comment]
The http://rdf.rubyforge.org/ site now redirects https://ruby-rdf.github.io/

**Comment by bendiken** [comment]
All subproject locations (e.g., http://rdf.rubyforge.org/raptor/) also now redirect to appropriate locations (e.g., https://ruby-rdf.github.io/rdf-raptor/).
